services:
  - type: static
    name: ai-tippmester-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "frontend/dist"
    envVars:
      - key: VITE_API_URL
        value: "https://ai-tippmester.onrender.com"
      - key: ENV_MODE
        value: "production"
